import type { Person } from "@/lib/data";

const weeklyPlayers = [
  ["王一桐", "wang-yitong"],
  ["姚孟妤", "yao-mengyu"],
  ["蒋茗朗", "jiang-minglang"],
  ["张皓博", "zhang-haobo"],
  ["闫政勋", "yan-zhengxun"],
  ["王晋宁", "wang-jinning"],
  ["田澄云", "tian-chengyun"],
  ["王亦龙", "wang-yilong"],
  ["王一帆", "wang-yifan"],
  ["张家瑞", "zhang-jiarui"],
  ["刘乙辰", "liu-yichen"],
  ["黄梓墨", "huang-zimo"],
  ["张晋铭", "zhang-jinming"],
  ["丁俊森", "ding-junsen"],
  ["齐梓恒", "qi-ziheng"],
  ["高铭阳", "gao-mingyang"],
  ["牟婉宁", "mou-wanning"],
  ["王瑞祥", "wang-ruixiang"],
  ["温泰实", "wen-taishi"],
  ["李柏霖", "li-bolin"],
  ["钟麟睿", "zhong-linrui"],
  ["韩迦南", "han-jianan"],
  ["单禹桥", "shan-yuqiao"],
  ["刘浙杰", "liu-zhejie"],
  ["王曦", "wang-xi"],
  ["邹淀瑞", "zou-dianrui"],
  ["李轩伊", "li-xuanyi"],
  ["徐安儿", "xu-aner"],
  ["姜博文", "jiang-bowen"],
  ["李冰远", "li-bingyuan"],
  ["韩沐廷", "han-muting"],
  ["王晗瑜", "wang-hanyu"],
  ["王洛柠", "wang-luoning"],
  ["李恒恺", "li-hengkai"],
  ["冯星尧", "feng-xingyao"],
  ["张千慧", "zhang-qianhui"],
  ["陈梦依", "chen-mengyi"],
  ["张俊熙", "zhang-junxi"],
  ["由子墨", "you-zimo"],
  ["姜凯超", "jiang-kaichao"],
  ["黄舒彤", "huang-shutong"],
  ["马启航", "ma-qihang"],
  ["康正喜", "kang-zhengxi"],
  ["李禹诺", "li-yunuo"],
  ["杨意可", "yang-yike"],
  ["李柏bo霖", "li-baibolin"],
  ["姜凯壹", "jiang-kaiyi"],
  ["郭逸瑞", "guo-yirui"],
  ["孙琰茹", "sun-yanru"],
  ["刘欣彤", "liu-xintong"],
  ["孙梦妍", "sun-mengyan"],
  ["黄梓博", "huang-zibo"],
  ["王星诺", "wang-xingnuo"],
  ["赵翔诚", "zhao-xiangcheng"],
  ["张景逸", "zhang-jingyi"],
  ["王羿程", "wang-yicheng"],
  ["王子睿", "wang-zirui"],
  ["张洪源", "zhang-hongyuan"],
  ["许梦隐", "xu-mengyin"],
  ["赵梓亦", "zhao-ziyi"],
  ["姜梓翼", "jiang-ziyi"],
  ["迟芷墨", "chi-zhimo"],
  ["禹昊辰", "yu-haochen"],
  ["隋芊缘", "sui-qianyuan"],
  ["农恩铭", "nong-enming"],
  ["王逸", "wang-yi"],
  ["李铭衍", "li-mingyan"],
  ["张豪格", "zhang-haoge"],
  ["张睿阳", "zhang-ruiyang"],
  ["张畅博", "zhang-changbo"],
  ["张景轩", "zhang-jingxuan"],
  ["张睿辰", "zhang-ruichen"],
  ["姜晓安", "jiang-xiaoan"],
  ["郑定琪", "zheng-dingqi"],
  ["宋治涵", "song-zhihan"],
  ["张青诺", "zhang-qingnuo"],
  ["李梓源", "li-ziyuan"],
  ["张涵涤", "zhang-handi"],
  ["李裕辰", "li-yuchen"],
  ["冯子琪", "feng-ziqi"],
  ["孟维杭", "meng-weihang"],
  ["单苑宁", "shan-yuanning"],
  ["王雨辰", "wang-yuchen"],
  ["李睿鹤", "li-ruihe"],
  ["陈隽宁", "chen-junning"],
  ["李张驰", "li-zhangchi"],
  ["冯则玮", "feng-zewei"],
  ["李祐萱", "li-youxuan"],
  ["孟思竣", "meng-sijun"],
  ["王芮茜", "wang-ruixi"],
  ["谭昊轩", "tan-haoxuan"],
  ["赵鹤轩", "zhao-hexuan"],
  ["王小畅", "wang-xiaochang"],
  ["齐梓恒", "qi-ziheng-319"],
  ["付晨鑫", "fu-chenxin"],
  ["韩沐遥", "han-muyao"],
  ["解紫妍", "xie-ziyan"],
  ["冯若闯", "feng-ruochuang"],
  ["王皓泽", "wang-haoze"],
  ["陈杜圻", "chen-duqi"],
  ["刘胤颉", "liu-yinjie"],
  ["吴梓翰", "wu-zihan"],
  ["李亦航", "li-yihang"],
  ["张梓洋", "zhang-ziyang"],
  ["闫星宸", "yan-xingchen"],
  ["宛佳智", "wan-jiazhi"],
  ["常文泽", "chang-wenze"],
  ["吴一凡", "wu-yifan"],
  ["李司诺", "li-sinuo"],
  ["李邦正", "li-bangzheng"],
  ["王呈诺", "wang-chengnuo"],
  ["唐嘉树", "tang-jiashu"],
  ["陈祉圻", "chen-zhiqi"],
  ["鲁屹泽", "lu-yize"],
  ["姜凯策", "jiang-kaice"]
] as const;

const femalePlayerNames = new Set([
  "姚孟妤",
  "牟婉宁",
  "王曦",
  "李轩伊",
  "徐安儿",
  "王晗瑜",
  "王洛柠",
  "张千慧",
  "陈梦依",
  "由子墨",
  "黄舒彤",
  "杨意可",
  "孙琰茹",
  "刘欣彤",
  "孙梦妍",
  "王星诺",
  "许梦隐",
  "迟芷墨",
  "隋芊缘",
  "王逸",
  "张景格",
  "姜晓安",
  "张涵涤",
  "王星诺",
  "牟婉宁",
  "冯则玮",
  "李祐萱",
  "王芮茜",
  "王小畅",
  "解紫妍",
  "李司诺",
  "王呈诺",
  "姜凯策"
]);

export const weeklyPlayerPeople: Person[] = weeklyPlayers.map(([name, slug]) => ({
  id: `weekly-${slug}`,
  slug,
  name,
  avatar: "/visuals/avatar-lin.svg",
  gender: femalePlayerNames.has(name) ? "女" : "男",
  roles: ["运动员"],
  city: "辽宁",
  mainEvent: "三阶速拧",
  bio: `${name} 是辽宁魔方少儿战队周赛选手，个人档案可继续关联登录账号、WCA 信息和历史周赛成绩。`,
  specialties: ["三阶", "周赛"],
  rankingNote: "周赛成绩已开始整理",
  visible: true
}));
